# Generated by Django 4.2.15 on 2026-03-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_url', models.URLField(help_text='Base URL of the service', unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(default='unknown', max_length=32)),
                ('last_message', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name', 'service_url'],
                'indexes': [models.Index(fields=['is_active', 'last_status'], name='serviceapps_is_acti_010135_idx'), models.Index(fields=['display_name'], name='serviceapps_display_8ce2b9_idx')],
            },
        ),
    ]
