# generated by Django for encrypting strings -- not used by the App Store
# see: https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-SECRET_KEY
SECRET_KEY = ''

# these values can be found in the Google APIs Console, located at:
#   https://code.google.com/apis/console
# then click on the "API Access" link on the left
GOOGLE_OAUTH2_CLIENT_ID     = '' # "Client ID" field in the console
GOOGLE_OAUTH2_CLIENT_SECRET = '' # "Client secret" field in the console
GOOGLE_API_KEY              = '' # "API key" field in the console
